### PR TITLE
Add an example for encrypted LVM using UDisks2 DBus API

### PR DESCRIPTION
**Pull request by vpodzime**

### CODE REVIEW

**Comment by dwlehman** [comment]
The requirements include (IIRC) a custom extent size of 8 MiB to showcase the ability to specify non-default parameters.

**Comment by vpodzime** [comment]
> The requirements include (IIRC) a custom extent size of 8 MiB to showcase the ability to specify non-default parameters.

Good catch! :)

**Comment by vpodzime** [comment]
> The requirements include (IIRC) a custom extent size of 8 MiB to showcase the ability to specify non-default parameters.
> 
> Good catch! :)

However, *udisks* doesn't support custom extent size.

**Review by vojtechtrefny — APPROVED** [review]
Looks good to me.

**Pull request merged**
